### ISSUE TITLE
Add support for Reolink Argus 3 MQTT detection events

### ISSUE THREAD

**Issue by 13** [QuantumEntangledAndy/neolink#109]
Could you add Person detection/vehicle detection as a MQTT message?

**Comment by QuantumEntangledAndy** [comment]
I have some of the code for this REd but unless I have a live camera to work on its nothing something I can fesibly add since none of my camera supports this

**Comment by QuantumEntangledAndy** [comment]
I am going to close this as not planned. If you want this feature please consider spending the time to implement it in a PR.
