### ISSUE TITLE
Argus 2 - Weird issue with BlueIris

### ISSUE THREAD

**Issue by Dinth** [QuantumEntangledAndy/neolink#114]
**Describe the bug**
Hi. Since i upgraded from https://github.com/thirtythreeforty/neolink to https://github.com/QuantumEntangledAndy/neolink im having a weird issue with BlueIris which i use as an NVR. 
Every time after neolink starts, BI detects my camera stream as vertical (containing about 1/3 third of the actual camera picture). Only if i reset the camera from within BI, it detects correct resolution of the camera stream. This is weird as i never had this problem with the original neolink nor any other camera.

**Expected behavior**
When i restart neolink as soon as the stream is available it should be detected in with the correct resolution.

**Versions**
NVR software: BlueIris (all versions - i have tried to downgrade it quite a lot to check if the issue still persists)
Neolink software: 0.5.13
Reolink camera model and firmware: Argus 2

**Comment by QuantumEntangledAndy** [comment]
This may have something to do with the dummy image we put up before we learn the true format. Theres a delay you see between setting up the rtsp server and getting the first real video frame from the camera. Before we get that frame we cannot reliably know the size of the image.

During this time I put up a dummy stream of static saying "Stream not Ready" of resolution 896x512. When the real connection is ready I drop all clients forcing them to reconnect. If I had to guess I'd say that BI is caching the resolution from that dummy connection rather then learning it again.

Do you have the pateince/time to test this?

**Comment by Dinth** [comment]
Time is not something i can promise with my current job, but i will try.
That's how it looks after neolink container restart:
![Screenshot from 2023-07-18 08-15-50](https://github.com/QuantumEntangledAndy/neolink/assets/313674/0bddfa46-4265-4425-9053-678701fc6c0f)
and how it looks after i reset the camera in BI:

![Screenshot from 2023-07-18 08-16-45](https://github.com/QuantumEntangledAndy/neolink/assets/313674/fb540a6a-1e5d-456a-af55-41b541c07712)

**Comment by QuantumEntangledAndy** [comment]
With the new splash = false option you will get the error `CRITICAL **: 18:32:17.260: could not create element` rather then getting the dummy video connection. Hopfully your BI retry until the camera is ready

**Comment by QuantumEntangledAndy** [comment]
The docker for testing this can also be found here `docker pull quantumentangledandy/neolink:feature-noSplash` if you use that instead of builds

**Comment by Dinth** [comment]
Hmmm, i think it is working with the docker container. 
Thank you very much.
I will be looking for bugs, etc for the next few days.

**Comment by QuantumEntangledAndy** [comment]
Anything to report with this? If not then I shall merge these changes

**Comment by Dinth** [comment]
it works flawlessly since i deployed it 2 weeks ago :)
