### ISSUE TITLE
PIR motion settings not working with Argus Eco

### ISSUE THREAD

**Issue by blipk** [QuantumEntangledAndy/neolink#12]
Hey @QuantumEntangledAndy 

Thanks for your work on attempting to get the PIR motion working and integrated with neolink.

However I'm having some trouble using the artifacts from the build here: https://github.com/QuantumEntangledAndy/neolink/actions/runs/3564809691

It stops the stream (twice) as soon as starting, and doesn't start up again when there's any motion.

Some info on my setup and devices here:
https://github.com/thirtythreeforty/neolink/issues/325

Full log file is attached.

[run.log](https://github.com/QuantumEntangledAndy/neolink/files/10109904/run.log)

Let me know if theres any more info you need.

**Comment by QuantumEntangledAndy** [comment]
Yeah I haven't quite finished the merge yet. I wrote the motion code so long ago I've forgotten a lot of how it worked. I might be easier if a rewrite some of it. I'll keep working at it when I've got the free time and see what I can do.

**Comment by blipk** [comment]
Thank @QuantumEntangledAndy 

Appreciate the work you're doing.
I ended up setting up SMTP alert on the PIR via the reolink software and triggering my NVR to record based on that, it doesn't seem overly reliable though.

Will check back once I've tested this setup and may see if there's anything I can do to help out with this merge.
