### ISSUE TITLE
BatteryInfo not always received

### ISSUE THREAD

**Issue by fmarzocca** [QuantumEntangledAndy/neolink#120]
In my neolink_config  I have set `print_format = "Xml"`, for my Argus Eco. 
Now it happens that every time I ask for status, I always receive the XML related to the rfAlarmCfg while the XML for BatteryInfo is received only if I try 2 or 3 times. It looks like a matter of timeout.

**Comment by QuantumEntangledAndy** [comment]
Which commands are you running? I might need to checkout the timeouts when I have some time as there seems to be more issues with them lately.

**Comment by fmarzocca** [comment]
`./neolink pir <name> --config=/homeAssets/neolink_config.toml`

**Comment by QuantumEntangledAndy** [comment]
Ok so my proposed changes for this are as follows.

- No longer report battery with pir
- Have a dedicated `battery` command to print battery when you actually need it

**Comment by fmarzocca** [comment]
I'm ok with this if it is reliable. Thanks

**Comment by QuantumEntangledAndy** [comment]
Should now be available in v0.5.18
