### ISSUE TITLE
Remote Camera Access - 4G

### ISSUE THREAD

**Issue by hblanken** [QuantumEntangledAndy/neolink#121]
**Describe the bug**
Awesome neolink fork! I am now testing the 4G relay connection to a Reolink Go Plus.
>
All works well from my office and from various Macs, with native neolink install.

But when I connect from overseas it fails.
How can this be?
I increased timeout time, I checked all ports open. Trace does not give me lot more info.

>
> UID: 95270005EUHXXXX ( I can provide you UID in DM)
>
> OFFICE -> Home
> It worked. After 5 retries.
> [2023-07-26T23:44:31Z INFO neolink_core::bc_protocol] 4Gcam1: Trying map discovery
> [2023-07-26T23:44:37Z INFO neolink_core::bc_protocol] 4Gcam1: Trying relay discovery
> [2023-07-26T23:44:42Z INFO neolink_core::bc_protocol] 4Gcam1: Discovery failed
> [2023-07-26T23:44:42Z WARN neolink::rtsp] 4Gcam1: Retryable error: 4Gcam1: Could not connect to camera
>
> Caused by:
> 0: Failed to connect to camera 4Gcam1 at UID: 95270005EXXX on channel 0
> 1: Cannot contact camera at given address
> [2023-07-26T23:44:42Z INFO neolink_core::bc_protocol] 4Gcam1: Trying map discovery
> [2023-07-26T23:44:47Z INFO neolink_core::bc_protocol] 4Gcam1: Trying relay discovery
> [2023-07-26T23:44:52Z INFO neolink_core::bc_protocol] 4Gcam1: Relay success 95270005XXX at 20.124.250.86:53262
> [2023-07-26T23:44:55Z INFO neolink::rtsp::states::loggedin] 4Gcam1: Camera time is already set: 2023-07-27 9:44:53.0 -10:00:00
> [2023-07-26T23:44:56Z INFO neolink::rtsp::states::loggedin] 4Gcam1: Camera reports firmware version v3.0.0.942_22041233
> [2023-07-26T23:44:56Z INFO neolink::rtsp::states::streaming] 4Gcam1: Starting video stream
> Main Stream (Clear)
> [2023-07-26T23:44:56Z INFO  neolink::rtsp::states::streaming] 4Gcam1: Starting video stream Sub Stream (Fluent)
>
> Overseas -> Fails
> [2023-07-27T10:49:00Z INFO  neolink] Neolink 52ad743bea54e545e834ab48eca6d35d97155af3 release
> [2023-07-27T10:49:00Z INFO  neolink::rtsp] Starting RTSP Server at X.X.X.X:XXXX
> [2023-07-27T10:49:00Z INFO  neolink_core::bc_protocol] 4gcam1: Trying map discovery
> [2023-07-27T10:49:05Z INFO  neolink_core::bc_protocol] 4gcam1: Trying relay discovery
> [2023-07-27T10:49:10Z INFO  neolink_core::bc_protocol] 4gcam1: Discovery failed
> [2023-07-27T10:49:10Z WARN  neolink::rtsp] 4gcam1: Retryable error: 4gcam1: Could not connect to camera
>
>    Caused by:
>        0: Failed to connect to camera 4gcam1 at UID: 9527000XXXXXXXXX on channel 0
>        1: Cannot contact camera at given address
> [2023-07-27T10:49:10Z INFO  neolink_core::bc_protocol] 4gcam1: Trying map discovery
> [2023-07-27T10:49:15Z INFO  neolink_core::bc_protocol] 4gcam1: Trying relay discovery
> [2023-07-27T10:49:20Z INFO  neolink_core::bc_protocol] 4gcam1: Discovery failed
> [2023-07-27T10:49:20Z WARN  neolink::rtsp] 4gcam1: Retryable error: 4gcam1: Could not connect to camera
>
>    Caused by:
>        0: Failed to connect to camera 4gcam1 at UID: 9527000XXXXXXXXX on channel 0
>        1: Cannot contact camera at given address
> [2023-07-27T10:49:20Z INFO  neolink_core::bc_protocol] 4gcam1: Trying map discovery
> [2023-07-27T10:49:25Z INFO  neolink_core::bc_protocol] 4gcam1: Trying relay discovery
> [2023-07-27T10:49:30Z INFO  neolink_core::bc_protocol] 4gcam1: Discovery failed
> [2023-07-27T10:49:30Z WARN  neolink::rtsp] 4gcam1: Retryable error: 4gcam1: Could not connect to camera
>
>    Caused by:
>        0: Failed to connect to camera 4gcam1 at UID: 9527000XXXXXXXXX on channel 0
>        1: Cannot contact camera at given address
> [2023-07-27T10:49:30Z INFO  neolink_core::bc_protocol] 4gcam1: Trying map discovery
> [2023-07-27T10:49:35Z INFO  neolink_core::bc_protocol] 4gcam1: Trying relay discovery
> [2023-07-27T10:49:40Z INFO  neolink_core::bc_protocol] 4gcam1: Discovery failed
> [2023-07-27T10:49:40Z WARN  neolink::rtsp] 4gcam1: Retryable error: 4gcam1: Could not connect to camera

**Comment by QuantumEntangledAndy** [comment]
Could you test using #123, builds are [here](https://github.com/QuantumEntangledAndy/neolink/actions/runs/5745890161?pr=123) or `docker pull quantumentangledandy/neolink:fix-async_lookup_and_register`

**Comment by hblanken** [comment]
@sqeeswy pull request and #123 work well! Thank you all for making it more robust!

**Comment by QuantumEntangledAndy** [comment]
Ok then I'm going to merge and push a release for later today.
