### ISSUE TITLE
tokio-runtime-worker

### ISSUE THREAD

**Issue by fmarzocca** [QuantumEntangledAndy/neolink#126]
Just installed new version 0.5.16

Now, by launching the command: `./neolink pir <camera-name> --config=/homeAssets/neolink_config.toml`

I am getting this error (in addition to the results):

`thread 'tokio-runtime-worker' panicked at 'A Tokio 1.x context was found, but it is being shutdown.', /github/home/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.29.1/src/runtime/time/entry.rs:557:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by QuantumEntangledAndy** [comment]
Yeah I have this for image too. Not actually an error. Its just that I don't shutdown all the threads gracefully.

**Comment by fmarzocca** [comment]
Ah! Ok, just try to be more graceful!
:-) :-)

**Comment by QuantumEntangledAndy** [comment]
Haha yeah its on the todo list. I have a fix in for image but need to add it to the other commands too

**Comment by QuantumEntangledAndy** [comment]
Changes for this are in, and will be released as part of v0.5.18

**Comment by QuantumEntangledAndy** [comment]
v0.5.18 is not out so this should be fixed. Please reopen if not
