### ISSUE TITLE
Add option to encode in h264

### ISSUE THREAD

**Issue by jgbaum** [QuantumEntangledAndy/neolink#130]
**Is your feature request related to a problem? Please describe.**
I'm using [scrypted](https://github.com/koush/scrypted) to pull the stream from neolink and feed it into my HomeKit network, but it doesn't like the h265 encoding.

**Describe the solution you'd like**
Would it be possible to add an option to set the encoding to h264?

**Comment by QuantumEntangledAndy** [comment]
We don't encode. Only pass on what the camera gives us. If I recall there is meant to be a way to change it from h265 to h264 from the official Reolink app somehow but it's not an obvious setting.

**Comment by QuantumEntangledAndy** [comment]
Here is the reddit article I was thinking of https://www.reddit.com/r/homeassistant/comments/sopd9a/hidden_h264_stream_in_reolink_rlc_810a_probably/ effectively the format is decided by the video size.

**Comment by jgbaum** [comment]
Perfect, thank you!
