### ISSUE TITLE
Latency vs original version

### ISSUE THREAD

**Issue by skylord123** [QuantumEntangledAndy/neolink#132]
**Describe the bug**
I have found that this fork actually adds 2-4 seconds onto the stream latency. Is there any reason for this and could it possibly be fixed? If I switch back to `thirtythreeforty/neolink` docker container the issue goes away and the stream is about 0.5-1 second of a delay.

I've done a few things to try and make this better such as switching to UDP but the issue is still there. This is really annoying if you have a camera that supports PTZ as you have to wait about 3 seconds until the camera moves. If I switch to the original container the latency is less and updates under a second.

**To Reproduce**
Testing this with PTZ is much easier as you can just press the move button and count the time that passes until the image updates. If you do not have PTZ you can test this by updating the time on the camera to match your system and compare the timestamp that shows on the image to your system's clock. I have a Node-RED automation to set/get the time off the camera so I use that to make sure the time is as close to correct as possible.

You need to test this on both this fork and the original to really see the added latency.

**Expected behavior**
I would expect latency that is similar to the original repo this one is forked from and be about a second or less.

**Versions**
NVR software: Xeoma 23.1.25 (Using UDP and made sure to have any buffering disabled)
Neolink software: latest (as of posting)
Reolink camera model and firmware: RLC-423ws with the last released firmware version

**Comment by kyle170** [comment]
Just chiming in here, I've tried to set the `buffer_size = 0` to each camera but I still get huge latency issues (+10 seconds, with it sometimes getting a couple of minutes behind) with the new version. The original version does not have these issues. Verified with Blueiris, HomeAssistant, Direct RTSP stream (VLC)

Example config below:
![image](https://github.com/QuantumEntangledAndy/neolink/assets/7320664/e0d2b45b-94ca-4671-9cd0-630e044d2a45)

Camera: Reolink Lumus
HW CPU: AMD Ryzen 5 3550H
HW LAN: 2.5Gbps
Running via Docker image on target machine (`thirtythreeforty/neolink:latest` && `QuantumEntangledAndy/neolink:latest`)

Is there something I'm doing wrong here?
