### ISSUE TITLE
Getting 404 from rtsp stream

### ISSUE THREAD

**Issue by savikko** [QuantumEntangledAndy/neolink#137]
Hi!

First of all, thanks for forking this project and maintaining it!

I am trying to run this first time here, having very simple config:
```toml
bind = "0.0.0.0"

[[cameras]]
name = "test"
username = "admin"
password = "secretpassword"
address = "192.168.20.222:9000"
```

Then, starting the neolink with
```
./neolink rtsp -c config.toml
```

It starts seemingly properly:
```log
[2023-08-21T20:50:09Z INFO  neolink::rtsp::states::loggedin] test: Camera reports firmware version v3.1.0.1643_22122302
[2023-08-21T20:50:09Z INFO  neolink::rtsp::states::streaming] test: Starting video stream Sub Stream (Fluent)
[2023-08-21T20:50:09Z INFO  neolink::rtsp::states::streaming] test: Starting video stream Main Stream (Clear)
```

Then, tried to open stream `rtsp://my_ip:8443/test` but no success, running
```
ffprobe rtsp://my_ip:8554/test
```

outputs
```
[rtsp @ 0x13fe04af0] method DESCRIBE failed: 404 Not Found
rtsp://my_ip:8554/test: Server returned 404 Not Found
```

What am I doing wrong here?

**Comment by QuantumEntangledAndy** [comment]
Ok so basic stuff first. 

You did replace my_ip with your actual ip right?

Do you ever got the message `buffers prepared` from neolink.

**Comment by savikko** [comment]
Yep, my_ip was just the placeholder for my ip here. And now double-confirmed it is correct.

```
[2023-08-22T06:31:19Z INFO  neolink::rtsp] test: Buffers prepared
```

This is the message I get also there (did not include it to first message as that hidden between debug messages :) ).

But, now I got this solved: I had some other process listening also on port 8554 and connection went to that process. Now changed `bind_port` and everything works :)

Thanks and sorry for the disturbance.
