### ISSUE TITLE
Audio backchannel (two-way audio)

### ISSUE THREAD

**Issue by savikko** [QuantumEntangledAndy/neolink#138]
I found this project while trying to get Reolink E1 Zoom to support two-way audio via go2rtc.

Go2rtc supports "[RTSP cameras](https://github.com/AlexxIT/go2rtc#source-rtsp) with [ONVIF Profile T](https://www.onvif.org/specs/stream/ONVIF-Streaming-Spec.pdf) (back channel connection)".

So the question is, does Neolink support that ONVIF Profile T?

I tried to investigate this from the source but being totally incompetent on RTSP, could not find out that by myself.

`neolink talk` works great on the camera.

**Comment by QuantumEntangledAndy** [comment]
Dosent do ONVIF at all. Id like to add it one day but since there is not many onvif server code available in rust it seems I'd have to implement it myself which will take some time.

**Comment by savikko** [comment]
Thanks, this clears up the situation.
