### ISSUE TITLE
RTSP: 404 Not found 

### ISSUE THREAD

**Issue by MicheleCardamone** [QuantumEntangledAndy/neolink#148]
The low FPS issue appears to have been corrected by updating to the latest firmware available for the B800 v3.0.0.183_21012800
However, I notice that of the 9 cams, each time one fails to connect to the stream, and on BlueIris only the Sub Stream appears, with the writing RTSP 404 not found. The problem is not with the cam in question, but with random rotation. Every time, at least one cam from this problem.
It also seems that when one of the cams presents this problem and I close Neolink, the cam in question is still receiving substreams even though Neolink is closed, as in the 2 attached photo

![Screenshot 2023-09-18 161442](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/7520ea3c-ead4-4def-98df-6434f290ee81)
![Screenshot 2023-09-18 162520](https://github.com/QuantumEntangledAndy/neolink/assets/102512971/5bcafb7a-80d7-429f-849e-d7145edc07e3)

**Comment by QuantumEntangledAndy** [comment]
404 occurs when it can connect to an rtsp server at the ip:port (`127.0.0.1:8554`) given but cannot find the url part (`/camname`). This can happen if the stream is taken too long for its initial configuration (where we query the camera to lean its format and resolution). How long of a delay between starting neolink and starting BI do you have? Can you make BI periodically retry 404 errors? It maybe that the default of BI is not to retry 404 since, 404 on a normal camera usually a user error on the url.

**Comment by QuantumEntangledAndy** [comment]
I could maybe make the server return a different error for when it is not ready (still will be a race to set that up, but a shorter one). But you will likely get other errors in BI until configuration is complete

**Comment by QuantumEntangledAndy** [comment]
So I went and looking into this. I can make it return a different error, a little earlier but not by a lot. Currently a stream is not created until a connection is made with the camera to confirm that 1. the camera exists, 2. the camera supports the requested stream (main/sub/extern). I'll send you the build with the slightly early point of media factory creation but it may be more reliable to just wait for a bit before starting BI or seeing if BI has a setting to retry 404s

**Comment by QuantumEntangledAndy** [comment]
Here's [the build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6230408510) I mentioned

**Comment by MicheleCardamone** [comment]
> So I went and looking into this. I can make it return a different error, a little earlier but not by a lot. Currently a stream is not created until a connection is made with the camera to confirm that 1. the camera exists, 2. the camera supports the requested stream (main/sub/extern). I'll send you the build with the slightly early point of media factory creation but it may be more reliable to just wait for a bit before starting BI or seeing if BI has a setting to retry 404s

I don't know if blueiris has a delay for 404. I just know that when I try to start neolink, blueiris is already started. I have always done this even with previous versions, is it wrong?

**Comment by QuantumEntangledAndy** [comment]
Right, and before I did not check if the camera was valid before starting a dummy rtsp media. Now I check, its a nice feature since it means that only valid streams will be started regardless of configuration

**Comment by QuantumEntangledAndy** [comment]
Ok [this build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6235409847) creates it even earlier in the process. It will return a 400 if you try to open a stream before it is ready now quite quickly since it relies just on the config to prepare that part without asking the camera what it supports. I hope BI retries 400 error codes

**Comment by MicheleCardamone** [comment]
> Ok [this build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6235409847) creates it even earlier in the process. It will return a 400 if you try to open a stream before it is ready now quite quickly since it relies just on the config to prepare that part without asking the camera what it supports. I hope BI retries 400 error codes

This Build seems to have solved the 404 error for me. The only problem seems to be the inconsistent fps. Some cams on the 20 fps sub stream in normal conditions suddenly go up to around 25 and then drop to around 15, same thing in the SubStream. It's the same problem as when "buffer_size" was not enabled in previous versions. Now in this build you said to no longer insert buffer size or use smoothing so I don't know how to adjust it.
In general, however, every type of other error seems to have been corrected. I leave it in testing hoping it doesn't generate any more "no signals". Congratulations for the work done

**Comment by QuantumEntangledAndy** [comment]
Seems that this issue is ok now so I'll close.

With regards to the smoothness, I am experimenting with the gstreamer jitter buffer rather then writing my own, hopefully I can get it to work
