### ISSUE TITLE
TOML parse error on mqtt with version 0.60

### ISSUE THREAD

**Issue by JC38** [QuantumEntangledAndy/neolink#151]
Hello,

Here is my problem. Maybe I made a mistake but i don't see where. Other eyes might see it.

**Describe the bug**
Launching neolink gives this error
Error: Failed to parse the "neolink.toml" config file

Caused by:
    TOML parse error at line 24, column 1
       |
    24 | [[mqtt]]
       | ^^^^^^^^^
    invalid type: map, expected a string

**To Reproduce**
Steps to reproduce the behavior. Example:
1. Create this configuration file:
`[[mqtt]]
server = "192.168x.y" # Address of the mqtt server
port = 1883 # mqtt servers port
credentials = ["MyUser", "MyPassword"] # mqtt server login details

[[users]]
name = "MyLoginName"
pass = "MyOtherPwd"
#

[[cameras]]
name = "E1"
...`

3. Launch Neolink: 

**Expected behavior**
Start Neolink

**Versions**
NVR software: none
Neolink software: 0.60
Reolink camera model and firmware: E1

**Comment by gyordanov** [comment]
same issue here ... removed the mqtt section to get it working, but it seem like now i don't get any events over mqtt

**Comment by QuantumEntangledAndy** [comment]
Use `[mqtt]` not `[[mqtt]]`. Single `[` is a table double is an array of tables

**Comment by QuantumEntangledAndy** [comment]
Seems I typod that in the read me. I'll try to get that fixed soon

**Comment by gyordanov** [comment]
thanks @QuantumEntangledAndy - single [ does indeed work ... i seem to have lost my mqtt sensors (all unavailable) but that is a different issue ... will try to rule out errors on my side first :)

**Comment by QuantumEntangledAndy** [comment]
Ok please open a new issue when you find it. I've pushed the readme update already so I'll close this one

**Comment by QuantumEntangledAndy** [comment]
Seems I inadvertently changed the online message from `connected` to `online`, need to change that back

**Comment by QuantumEntangledAndy** [comment]
Build that uses `connected` over `online` is [here](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6281774372) (will take about an hour to compile) please see if it fixes your sensors

**Comment by QuantumEntangledAndy** [comment]
Ok so I've had a few errors associated with MQTT there should be a 0.6.1 build coming out soon that addresses these issues. When it is released I'd appreciate a test of the HA part of it

**Comment by gyordanov** [comment]
@QuantumEntangledAndy reinstalled the addon in HA and the sensors work now !!!

i got confused as the neolink executable still reports v0.6.0 but it works now!
