### ISSUE TITLE
Awaking through notification works for a limited time

### ISSUE THREAD

**Issue by Adammantium** [QuantumEntangledAndy/neolink#166]
**Describe the bug**
Hello, its me again, sorry to bother you again.
I had a issue with the cameras not going to idle a few days ago, now i have to opposite issue. The notification waking doesn't seem to work properly.
If i start the program it will work for half an hour or something, but then it wont wake up again.
I also tried resetting the `neolink_token.toml` with no change in behaviour.

**To Reproduce**
Steps to reproduce the behavior. Example:
1. Create this configuration file:
```
bind = "0.0.0.0"

[mqtt]
broker_addr = "127.0.0.1" # Address of the mqtt server
port = 1883 # mqtt servers port
credentials = ["main", "qnuVMFNj0sfkGOgUhCgmJnGNofAYQV"] # mqtt server login details

[[cameras]]
name = "reolink1"
username = "admin"
password = ""****"
uid = "****"
address = ""****.151"
stream = "both"
idle = true
discovery = "local"

[[cameras]]
name = "reolink2"
username = "admin"
password = ""****"
uid = ""****"
address = ""****.157"
stream = "both"
idle = true
discovery = "local"

[cameras.mqtt.discovery]
topic = "homeassistant"
features = ["camera", "ir", "motion", "battery"]
```
2. Launch Neolink: neolink mqtt --config ...

**Expected behavior**
The cameras will wake up by the notification.
I tested it on 2 different phones, they are getting the reolink app notification, just the neolink service wont wake up.

**Versions**
NVR software:
Neolink software: c09bc13598552c3d2a026a3abd422f1c83330bff (+last few version of the [feature/push_mqtt](https://github.com/QuantumEntangledAndy/neolink/tree/feature/push_mqtt) branch)
Reolink camera model and firmware: Reolink Argus Eco (v3.0.0.1981_23040606)
OS: Linux Debian 12

[Log.txt](https://github.com/QuantumEntangledAndy/neolink/files/12805433/Log.txt)
Let me know if you need any of the IDs or if i can test some other stuff.

**Comment by QuantumEntangledAndy** [comment]
Lets try something in the log there is a `push notification UID: [PUSH_NOT_ID_2]` that UID is something we generate when registering

Can you run this command in the terminal (assuming you have curl installed)

```bash
curl -X GET 'https://pushx.reolink.com/listeners/[PUSH_NOT_ID_2]/devices' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept: */*' -H 'Accept-Language: en-GB,en; q=0.9' -H 'Cookie:'
```

It will ask reolink to report on all cameras registered with that push id, can you see if reolink unregistered it

Success should look something like this

```
{"status":{"code":0,"detail":"OK"},"data":[{"uid":"UID","secret":"CHARS"}]}
```

**Comment by Adammantium** [comment]
Seems to work fine:
```
{"status":{"code":0,"detail":"OK"},"data":[{"uid":"uui of cam 1","secret":"..."},{"uid":"uuid of cam 2","secret":"..."}]}
```
I can send you the uncensored stuff via mail if you need it.

**Comment by Adammantium** [comment]
I just checked pi hole and i can see the server is definitely doing something:
![image](https://github.com/QuantumEntangledAndy/neolink/assets/38858318/e5b6f893-3406-494b-a1b5-7c0a09186fd7)
Nothing in the neolink log, but its pulling the pushx domain.

**Comment by QuantumEntangledAndy** [comment]
Then I'm not quite sure. Perhaps I am meant to reregister the FCM from time to time, but I havent seen anything to indicate that I should do that

**Comment by Adammantium** [comment]
If you send me like a curl command i can try sending it manually via cron and ill see if that helps.
The google domains are contacted successfully when starting:
![image](https://github.com/QuantumEntangledAndy/neolink/assets/38858318/024bbe50-015a-41d6-94ef-eb1662eb8da2)

**Comment by QuantumEntangledAndy** [comment]
Most of this I just delegate to https://github.com/RandomEngy/fcm-push-listener 

Can you tell if the socket to mtalk.google.com:5228 is kept open?

**Comment by Adammantium** [comment]
Seems like its open:
```
tcp   ESTAB      0      0    192.168.178.10:52676   108.177.15.188:5228
tcp   ESTAB      0      0    192.168.178.10:52690   108.177.15.188:5228
```

**Comment by QuantumEntangledAndy** [comment]
Do you know if you are in the connected or disconnected state? When you get a push notfication, perhaps it dosent' send if the camera says we are connected to them

**Comment by Adammantium** [comment]
I will  check it again, we just got some new cameras, i will try it with them so i dont have to run outside the whole time :)

**Comment by Adammantium** [comment]
Okay, so, i just did some testing, the notifcations didnt work at first while it was connected, it looked like motion stayed off, wenn the cameras disconnected and i waved infront of cam 3, it reconnected cam 1 and updated the notification on there, cam 3 stayed disconnected with the old notification.

**Comment by Adammantium** [comment]
![image](https://github.com/QuantumEntangledAndy/neolink/assets/38858318/f4a85086-1fd1-45eb-b840-474b1724aa51)

**Comment by Adammantium** [comment]
Okay, now its not working anymore at all, i left it disconnected for 30 minutes. No camera is waking up now, but the notification on the phone still works.
The sockets are still open and connected as well.

**Comment by QuantumEntangledAndy** [comment]
So basic things to ask. 

- Has the last will been sent (offline on the neolink/status)
- is there anything in the log about any threads stopping?

**Comment by Adammantium** [comment]
> * Has the last will been sent (offline on the neolink/status)  

neolink status is on connected
![image](https://github.com/QuantumEntangledAndy/neolink/assets/38858318/c363a3a3-a960-4304-90bb-43a5746152e2)


> * is there anything in the log about any threads stopping?

Nope, nothing, last message is the shutdown stuff:
```
Okt 05 14:09:04 srv neolink[1511486]: [2023-10-05T12:09:04Z DEBUG neolink::common::neocam] reolink3: Idle
Okt 05 14:09:04 srv neolink[1511486]: [2023-10-05T12:09:04Z DEBUG neolink::common::neocam] reolink3: Disconnect On Request
Okt 05 14:09:04 srv neolink[1511486]: [2023-10-05T12:09:04Z DEBUG neolink_core::bc_protocol::connection::bcconn] BcConnection::shutdown Cancel
Okt 05 14:09:04 srv neolink[1511486]: [2023-10-05T12:09:04Z DEBUG neolink_core::bc_protocol::connection::udpsource] UdpPayloadInner::new SendToSocket Cancel
```

> * does it reconnect when you use mqtt explorer to post the `neolink/camname/query/preview` message

Yes, this works perfectly fine, will immediately connect the camera and update the preview.
It wont update the notification nor will it fix the issue with waking up, it will still not wake on notification as soon as its disconnected again.

**Comment by QuantumEntangledAndy** [comment]
Sure I just wanted to check if the wake up was broken, these sort of question help narrow down the source. So if I an understanding this right it just wakes up one of the cameras? Perhaps I need to change the push UID to be unique for each camera or do it from a central interface

**Comment by Adammantium** [comment]
So in summary:

- When I start neolink and all cameras go to idle, if i wave infront of camera 3 it will wake up camera 1.
- If i wait 30 minutes or so before waving to a camera, it wont wake up any camera, nothing inside the log
- If i execute the command `neolink/reolink3/query/preview` it will wake up the correct camera and update the preview.

Maybe you dont need different UIDs for each camera and the push notification. It seems like the notification itself contains the UID already, so you can probably determine the camera this way.
I dont know if its already using that.

**Comment by QuantumEntangledAndy** [comment]
Yes thats the alternative to create central fcm receiver and pass the messages to the right camera. Would be a larger refractor though and would mean also storing the UID somewhere in the camera data which I don't actual do atm. So going to make them unique first

**Comment by Adammantium** [comment]
I just restarted neolink and tested again, now camera 2 reacted to motion of camera 3. So its probably the last socket that got registered for push notifications that will handle all notifications.

**Comment by QuantumEntangledAndy** [comment]
Im going to put in the work to make a central push notification receiver since I want only the one config file and having it read/write by three different threads at once is just asking for race errors.

**Comment by Adammantium** [comment]
I really appreciate the effort

**Comment by Adammantium** [comment]
It seems like I can't download the builds anymore. The builds on the buttom don't let me click them anymore.
Can you send me a direct link to the amd64 linux file?

**Comment by Adammantium** [comment]
Okay, i was able to download it from my phone. I will test it later today :)

**Comment by QuantumEntangledAndy** [comment]
Have to be logged in to see a download link so maybe it was that. Or maybe it wasn't built yet. Sometimes I send a link while building, usually when I need to do something else and don't have time to follow up.

**Comment by Adammantium** [comment]
Yeah, i wasn't logged in. That was probably it.

I tested the version, and the issue seems to be the same. After about half an hour the cameras dont wake up again, no messages in the console.
I'm currently not at home so I can't check MQTT directly.

I will do some more testing in about 6 hours.

**Comment by Adammantium** [comment]
I haven't completely tested if its waking up the correct camera yet. But from what i was seeing inside the log, it seems to be working.

**Comment by Adammantium** [comment]
Okay, i tested it some more. So its waking up the correct camera that triggered the notification and its only updating the notification on that specific camera in MQTT.
But its still not waking them up if they have idled for like 30 minutes. No messages inside the log as well.

**Comment by Adammantium** [comment]
Just tested the [Neolink 0.6.3-rc.1](https://github.com/QuantumEntangledAndy/neolink/releases/tag/v0.6.3.rc.1). It seems to be working and is waking up the cameras on notification now. But it also wakes them up every few minutes draining the battery. Is there a option im missing?

**Comment by QuantumEntangledAndy** [comment]
I noticed that too. I think it's the re-re-registration of the push notifications. Think of got it fixed on my testing branch but haven't had a chance to actually test it.

**Comment by Adammantium** [comment]
Let me know if you need someone to test it

**Comment by QuantumEntangledAndy** [comment]
Sure try [this build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6688588026)

**Comment by Adammantium** [comment]
Just tested the build, it still wakes up the camera every few minutes without a notification.
Seems like the reregistering of the notification will receive the last notification the camera send. So its waking up the camera again, maybe you need to remember the timestamp or something from the last notification and only wake up from a notification if its not the same as the last one.

**Comment by QuantumEntangledAndy** [comment]
We cache the uid of the notification to filter them. But Perhaps it's in the notification part further down if it's restarting because of an error.

**Comment by Adammantium** [comment]
I checked the log, I can't see any errors. I'll send it later

**Comment by Adammantium** [comment]
[neolink.log](https://github.com/QuantumEntangledAndy/neolink/files/13226695/neolink.log)

**Comment by Adammantium** [comment]
Any update on this?
Seems like the current master branch is pretty solid.
Sometimes I'm having the issue that a few cams keep getting activated.
It seems to happen as soon as the first notification comes in, it will always trigger with the same one, even hours after the specified Alarm Time inside the notification. It just seems like its getting stuck with that one notification, maybe it's not getting dismissed and it keeps to be sent to neolink?
Is there a way to clear the notifications?

**Comment by QuantumEntangledAndy** [comment]
I actually have a fix in on another branch. I'm just waiting on some reports from other users about stability

**Comment by Adammantium** [comment]
What branch is it, I would be happy to test :)

**Comment by Adammantium** [comment]
For the last day it was working flawlessly.
The cameras woke up on movement and my push notifications through home assistant where pretty much on point.
There was no high battery drain, they even charged by 2-3%.
I will reopen this ticket if the issue comes back, but for now i consider it solved!

Thank you 👍

**Comment by Adammantium** [comment]
Update: Still running perfectly fine, no restarts needed, no battery drain
