### ISSUE TITLE
Static image instead of noise

### ISSUE THREAD

**Issue by fsedarkalex** [QuantumEntangledAndy/neolink#169]
**Is your feature request related to a problem? Please describe.**
Kind of.
I am using neolink and feeding the camera's stream into Frigate for object/person detection.
Tonight my camera's battery went low and it got disconnected. neolink now seems to send "white noise". This causes frigate to use up a lot of CPU resources as lots of the pixel constantly change.
![image](https://github.com/QuantumEntangledAndy/neolink/assets/16449266/3971c41a-7d6c-4eb1-b63f-23ad2fae0352)

**Describe the solution you'd like**
I would like to see a switch to change this behavior - maybe per camera.
I would propose three options:
- White Noise (default)
- Last captured image
- A static image (maybe a file provided by the user)
All of them should include the "Stream not ready" text though.

**Comment by bwthor** [comment]
I've seen my BlueIris crash a few times when that screen is playing.  Not sure if it was because the loss of the camera feed or what, but I vote for a static image too.

**Comment by QuantumEntangledAndy** [comment]
With BI it's best to have it disabled with splash=false otherwise it can mess up the resolution.

**Comment by QuantumEntangledAndy** [comment]
It should already push the last image, (unless neolink restarts). That screen should only be visible before the very first camera `Avaliable at` before we get the first frame. This screen is the placeholder until the first frame has arrived. If this isn't the case please tell me some more details such as logs

I can however swap to a black screen or anything else you want from here https://gstreamer.freedesktop.org/documentation/videotestsrc/index.html?gi-language=c#GstVideoTestSrcPattern

**Comment by QuantumEntangledAndy** [comment]
Ok in [this build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/6543097284) I've added the config option `splash_pattern` thats takes any of the pattern in https://gstreamer.freedesktop.org/documentation/videotestsrc/index.html?gi-language=c#GstVideoTestSrcPattern e.g. `splash_pattern = "black"`

**Comment by QuantumEntangledAndy** [comment]
I'll close this one as complete for the enhancement but please do let me know if yove got an issue with the last image

**Comment by fsedarkalex** [comment]
I encountered this once overnight. In all other cases, I have seen this splash screen after a neolink restart.
So maybe in this single case, neolink had crashed overnight and I did not notice.

BUT: I am currently running on the mqtt_push branch and there after some idle time, **sometimes** I do not receive an image anymore. I'll try to get logs from such a case and open a new issue for this, as I think its something different.

**Comment by fsedarkalex** [comment]
@QuantumEntangledAndy 

Today I got some time for testing again and I spun up neoling on the rc1 version, connecting to an argus 3 pro battery camera.
It disconnects about 22seconds (not 30) and shortly after frigate complains.

If you connect VLC to neolink directly, the stream starts and after exactly 22 seconds the image freezes and some seconds later VLC turns into "STOPPED" state as if the stream had ended.

No last image.

```
frigate  | 2023-10-29 10:04:15.200655868  10:04:15.200 WRN github.com/AlexxIT/go2rtc/internal/streams/producer.go:171 > error="read tcp 172.18.0.2:56574->192.168.170.211:9999: i/o timeout" url=rtsp://...

[...]

frigate  | 2023-10-29 10:07:41.038373306  [2023-10-29 10:07:41] watchdog.akkutest              ERROR   : Ffmpeg process crashed unexpectedly for akkutest.
frigate  | 2023-10-29 10:07:41.038457214  [2023-10-29 10:07:41] watchdog.akkutest              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2023-10-29 10:07:41.038520763  [2023-10-29 10:07:41] ffmpeg.akkutest.detect         ERROR   : rtsp://192.168.170.211:8554/akkutest_sub: Invalid data found when processing input
frigate  | 2023-10-29 10:07:46.175575312  [2023-10-29 10:07:46] frigate.video                  ERROR   : akkutest: Unable to read frames from ffmpeg process.
frigate  | 2023-10-29 10:07:46.175890584  [2023-10-29 10:07:46] frigate.video                  ERROR   : akkutest: ffmpeg process is not running. exiting capture thread...
frigate  | 2023-10-29 10:07:51.065358857  [2023-10-29 10:07:51] watchdog.akkutest              ERROR   : Ffmpeg process crashed unexpectedly for akkutest.
frigate  | 2023-10-29 10:07:51.077103270  [2023-10-29 10:07:51] watchdog.akkutest              ERROR   : The following ffmpeg logs include the last 100 lines prior to exit.
frigate  | 2023-10-29 10:07:51.077727481  [2023-10-29 10:07:51] ffmpeg.akkutest.detect         ERROR   : rtsp://192.168.170.211:8554/akkutest_sub: Invalid data found when processing input
frigate  | 2023-10-29 10:07:53.558873515  10:07:53.558 WRN [rtsp] error="streams: codecs not matched: H264, S16B => H264, H265, AAC" stream=akkutest_sub

```

**Comment by QuantumEntangledAndy** [comment]
Your using `idle_disconnects` right? While in a disconnected state frigate gets no frames so it complains. When i tested Frigate though I just ignored thoses error until the connection resumes and it seemed to reconnect fine

**Comment by QuantumEntangledAndy** [comment]
On `idle_disconnect` VLC will also go into the stop state. The only client I know that works across pause is `ffplay` and `ffmpeg`

There's no good way to repeat a pause frame without causing issues

**Comment by QuantumEntangledAndy** [comment]
Long story short the client sees no frames and decides "oh the stream must have stopped I'll close". Only certain clients that have settings that will wait the needed time can see it accross a pause boundary.

Frigate from my tests just seems to repeat that error message forever then resume as normal when it is back online

**Comment by fsedarkalex** [comment]
Ah! I see! Thanks for clarifying this!
