### ISSUE TITLE
MQTT Discovery - Add Actions

### ISSUE THREAD

**Issue by fsedarkalex** [QuantumEntangledAndy/neolink#176]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I'd like to see Homeassistant auto-discovering the new mqtt wakeup command as service. Maybe same for other control topics, that are yet undiscovered

**Comment by QuantumEntangledAndy** [comment]
Sure, do you think you could PR it? Just need to add it to src/mqtt/discovery.rs
