### ISSUE TITLE
0.6.3 High Memory Consumption until system crashed

### ISSUE THREAD

**Issue by jerryj001** [QuantumEntangledAndy/neolink#183]
Installed 0.6.3 , Memory usage is high and constantly increasing when running with Frigate. It crashed system in the end. Restarted system several times, also change configurations of both Frigate and Neolink, didn't solve the problem. In the end, reversing back to 0.6.2 solved the problem

**To Reproduce**
1. Install 0.6.3;
2. run with Frigate

**Versions**
NVR software: Frigate 0.12.1
Neolink software: 0.6.2
Reolink camera model and firmware: Lumus v2.0.0.705_21052800
Ubuntu  22.04.3 LTS

**Comment by Sinnedterklaas** [comment]
I'm running Neolink on Home Assistant using the fork of d82m. Running this on a Intel Nuc with a celeron n3050. I had much more delay and more cpu/ram usage than version using the last 0.6.3 compared to version 0.6.2

I'm also using this with a Reolink Lumus v2.0.0.705_21052800 - so something seems to be going on with this combination.

**Comment by FLAYYMz** [comment]
Same issue. Started getting outages of all services running on my Synology NAS. Resource manager shows 9gb RAM used by neolink. Killed the container, and finally my services are responsive again.

**Comment by dan-r** [comment]
Same here, with my Lumus and that firmware version my delay was getting to 2+ minutes vs ~5 seconds with v0.6.1.

**Comment by skywurz** [comment]
Came here to say the same. I have set --restart=on-failure --memory="10g" on my container to prevent full system lockup and the container eats the 10gb and crashes every 2 days.

**Comment by JC38** [comment]
Same here for the RC1
![image](https://github.com/QuantumEntangledAndy/neolink/assets/16527222/5165855e-c3da-4990-87de-5f6246355a45)

**Comment by Beer17HWAM** [comment]
Same here with Neolink 0.6.3-rc.1 on Debian Bookworm. Delay is geting more and more after new start.
![neolink](https://github.com/QuantumEntangledAndy/neolink/assets/97590748/d26f91b1-7e05-4195-a677-e63734c31949)

**Comment by QuantumEntangledAndy** [comment]
Hopefully this is now fixed in latest. If anyone could confirm that would be nice

**Comment by JC38** [comment]
Andrew, 
Thanks for this information. 
But which latest version are you speaking about ? Is it the 0.6.3 rc1 or a newer ? If there is a newer, is it possible to add it into the releases section plz ?

**Comment by Beer17HWAM** [comment]
> Hopefully this is now fixed in latest. If anyone could confirm that would be nice

I don't see a newer (recent) version than 0.6.3-rc.1 either. The 0.6.3-rc.1 has this memory issue: https://github.com/QuantumEntangledAndy/neolink/issues/183#issuecomment-1893949317

**Comment by QuantumEntangledAndy** [comment]
The very tip of the branch here I'll link the test binaries https://github.com/QuantumEntangledAndy/neolink/actions/runs/8843106799 they are at the bottom of the page

**Comment by JC38** [comment]
I can see these lines into the log
![image](https://github.com/QuantumEntangledAndy/neolink/assets/16527222/a2e54e6d-e614-4bb0-8742-a9fe0d61d0b1)
What are they ?
CPU is higher than rc1 and memory footprint too but I guess it could be related to the debug version.
I'll check if memory used increase or not after some hours.

**Comment by QuantumEntangledAndy** [comment]
Oh that is to do with the push notifications. It needs to store the credentials somewhere and by default that is $HOME/.config but since you have it running as a services with no homedir it is erroring out.

**Comment by JC38** [comment]
Hello,

Something happened during the night that made Neolink using all the CPU
![image](https://github.com/QuantumEntangledAndy/neolink/assets/16527222/3a974969-5c6f-471b-96ff-23ee9eb4aed0)

![image](https://github.com/QuantumEntangledAndy/neolink/assets/16527222/f008a12a-7a88-4653-b7a7-8a05c748f54e)
It happened at 2 am. This is the day and time where there is a reboot scheduled into the Reolink E1 :-(.

For the memory, this is too early to say it is better or not. On the graph below, every lowest point corresponds to the start of the service.
![image](https://github.com/QuantumEntangledAndy/neolink/assets/16527222/529257e6-45bb-40c9-8927-eed03f26168a)
