### ISSUE TITLE
Motion detection with floodlight only

### ISSUE THREAD

**Issue by tiwo85** [QuantumEntangledAndy/neolink#196]
**Describe the bug**
Reolink Floodlight Wifi
Motion Sensor ist Not working. In Version 0.5.13 Sensor ist Off. In V 0.6.x sensor ist unknown

**Versions**
Neolink software:
0.5.13 
0.6.2
0.6.3-rc1
Reolink camera model and firmware:
Reolink Floodlight Wifi
v3.0.0.1311_22090740

**Comment by kylepyke** [comment]
Also having this issue

**Comment by QuantumEntangledAndy** [comment]
So these floodlights don't have what reolink calls motion. They have a PIR instead which is detected and handelled differently in the code. As far as I can tell theres noway for me to connect and listen to PIR except via push notifications. The PIR seems to be handelled by the camera to then drive camera actions like turning on the lights or sending a push notification. Unless I can find a event from the camera that shows the motion as active I can't address this
