### ISSUE TITLE
mqtt "enable_preview = false" has no effect

### ISSUE THREAD

**Issue by zimbo86** [QuantumEntangledAndy/neolink#203]
**Describe the bug**
When setting 
`enable_preview = false`
in mqtt section a preview snapshot is still published every 2sec to neolink/cam/status/preview

**To Reproduce**
Steps to reproduce the behavior. Example:
1. Add "enable_preview = false" to [mqtt]
2. Restart neolink

**Expected behavior**
No messages published every 2sec

**Versions**
NVR software: 
Neolink software: latest docker build
Reolink camera model and firmware: Lumus

**Comment by judasferret** [comment]
I'm also seeing this issue on a range of cameras. Work around is to set mqtt.preview_update = really big number. This bug destroys your battery cameras. 

Version: Neolink e47a0d5734b0a06b53bd8d78be9ca2f6b8396480 release neolink 0.6.2
OS: Windows 11
Cameras: Reolink Battery Cameras: TrackMix, Argus Pro 3, PT

**Comment by QuantumEntangledAndy** [comment]
It should be set in `[cameras.mqtt]` not `[mqtt]`
