### ISSUE TITLE
Only mqtt but stable 

### ISSUE THREAD

**Issue by Beer17HWAM** [QuantumEntangledAndy/neolink#206]
Hi,
Thanks for developing this great tool to use Reolink Lumus for motion detection and entity pictures in combination with Home Assistant.
I used the rc with the the mqtt parameter but it's not stable. I only want to use motion detection and snapshot pictures. I send the entity picture to Telegram on motion. Perfect. But after some hours of running it's stopping. It's not updating anything anymore. I must stop the application and start again.
Now I am trying the last normal version, not the rc. I hope this is better.
But my question:
Is this tool still in development?
Can you please make it more stable?
Thanks in advance.

**Comment by Beer17HWAM** [comment]
After a few hours also version 0.6.2 stops updating the preview picture. The motion sensor keeps working and also the floodlight can be controlled. So only the picture isn't updated anymore. I can see this with the application MQTT Explorer. Please take a look at this.

**Comment by QuantumEntangledAndy** [comment]
This may have something to do with the retry mechanic failing. Hopefully this is addressed now, let me know if not
