### ISSUE TITLE
does it really work on a raspberry pi 3? - libssl.so.3 error

### ISSUE THREAD

**Issue by Sen5ation** [QuantumEntangledAndy/neolink#210]
**Describe the bug**
i downloaded the latest version, copied it and add some execution rights to it, but it does not seem to work:
```
  573  wget https://github.com/QuantumEntangledAndy/neolink/releases/download/v0.6.3.rc.1/neolink_linux_armhf.zip
  574  unzip neolink_linux_armhf.zip
  575  cd neolink_linux_armhf/
  576  ll
  577  sudo cp neolink /usr/local/bin/
  578  sudo chmod +x /usr/local/bin/neolink
  579  /usr/local/bin/neolink rtsp --config sample_config.toml
```

when I executed the last command, i get this:
```
/usr/local/bin/neolink: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory
```

**To Reproduce**
download the latest version and run it on a rapspberry pi 3

**Expected behavior**
a normal start of neolink

**Versions**
NVR software: -
Neolink software: v0.6.3
Reolink camera model and firmware: -

**Comment by QuantumEntangledAndy** [comment]
Can you confirm you have all the dependencies installed including openssl. Since your missing the libssl library I would suspect not.

**Comment by freemlab** [comment]
I have the same problem on raspberry pi 4. Openssl is installed

**Comment by patSmartHome** [comment]
I have the same issue on raspberry pi 3 using following os version:
PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye

The actual libssl version is libssl-dev:armhf (1.1.1w-0+deb11u1+rpt1)
