### ISSUE TITLE
Thanks for helping with enabling the camera's HTTP server.

### ISSUE THREAD

**Issue by ericlathrop** [QuantumEntangledAndy/neolink#248]
Yesterday I submitted https://github.com/thirtythreeforty/neolink/issues/383 and you pointed me to the new `services` command. I was able to use that command to enable the HTTP server on my cameras. The command was basically `neolink services --config /etc/neolink.toml Camera01 http on`. I wrote up a longer version of the story at https://ericlathrop.com/2024/05/enabling-http-on-a-reolink-camera-after-a-firmware-upgrade/

Thanks so much for your help, and for maintaining this project. I sent a few dollars to your Ko-fi.

**Comment by QuantumEntangledAndy** [comment]
Glad you managed to get it to work. You can also download CI binaries from the actions tab on github if you don't feel like pulling a docker https://github.com/QuantumEntangledAndy/neolink/actions/workflows/build.yml?query=branch%3Amaster+
