### ISSUE TITLE
Login credentials were not accepted

### ISSUE THREAD

**Issue by SirConfigMgr** [QuantumEntangledAndy/neolink#250]
**Describe the bug**
I get the following error message in the log:
"Login credentials were not accepted"

In the Reolink app, however, the credentials work.

Config:

bind = “0.0.0.0”
[[cameras]]
name = “Wohnzimmer”
username = “admin”
pass = “xxx”
address = “xxx.xxx.xxx.xxx:9000”
uid = “xxx”

[[cameras]]
name = “Terrasse”
username = “admin”
pass = “xxx”
address = “xxx.xxx.xxx.xxx:9000”
uid = “xxx”

**To Reproduce**
The problem occurs continuously.

**Expected behavior**
The connection should be established successfully.

**Versions**
NVR software: - 
Neolink software: 0.6.3-rc.2
Reolink camera model and firmware:
E1 Pro - v3.0.0.2356_23062004
Lumus - v2.0.0.705_21052800

**Comment by QuantumEntangledAndy** [comment]
Please replace `pass` with `password`.
