### ISSUE TITLE
Support building a MQTT-only version without the gstreamer dependency 

### ISSUE THREAD

**Issue by MatthiasPetermann** [QuantumEntangledAndy/neolink#287]
I did an experimental fork (https://github.com/MatthiasPetermann/neolink) which removes all dependencies (and functionality) with regard to gstreamer. My goal was to leverage neolink as a MQTT bridge for multiple cameras on a minimal Alpine Linux container using musl. A static binary without external dependencies was required, and hence RTSP was not in my requirements list, instead of fixing build dependencies or switch to another base image removing gstreamer was a viable option. 

I'm not a Rust expert, but I think it would be great if there was a way to avoid forking and instead make the GStreamer dependencies a build-time toggle.

**Comment by QuantumEntangledAndy** [comment]
I can lock it behind a feature flag but I am not likely to provide builds for it. You'd have to build it yourself

**Comment by QuantumEntangledAndy** [comment]
You'd probably also need tot do something similar with the push request code as that build on protobuff and openssl libs

**Comment by QuantumEntangledAndy** [comment]
This commit https://github.com/QuantumEntangledAndy/neolink/commit/3349486750f24157dbd062e15eb2ea2adc61b911 makes it a build time dependency which you can build with

- no gstreamer or pushnoti

```bash
cargo build --release --no-default-features
```

- no gstreamer, but have pushnoti

```bash
cargo build --release --no-default-features --features=pushnoti
```

- no pushnofi but have gstreamer

```bash
cargo build --release --no-default-features --features=gstreamer
```

---

Not sure how well I can maintain it going forward since it is such a deep change I might miss something during a build someday

**Comment by MatthiasPetermann** [comment]
@QuantumEntangledAndy Thank you very much for your thoughts and the quick implementation. I was able to test it successfully and am pleased that there is now a clean solution available that doesn't require patching the original source. It's perfectly fine with me if there won't be any official binaries for this configuration. Thanks again, and have a good weekend! Matthias

**Comment by QuantumEntangledAndy** [comment]
Glad to be helpful...


...now if only tracing the mem leak was as easy as this one :)


Anyways take care yourself and have a good weekend too
