### ISSUE TITLE
PHONE_REGISTRATION_ERROR on pre-release

### ISSUE THREAD

**Issue by Akyariss** [QuantumEntangledAndy/neolink#295]
**Describe the bug**
Error on console when using both latest pre-releases [Neolink 0.6.3-rc.2] and [Neolink 0.6.3-rc.2]

WARN  neolink::common::pushnoti] Issue connecting to push notifications server: ServerError("PHONE_REGISTRATION_ERROR")

**To Reproduce**
Steps to reproduce the behavior. Example:
1. Create this configuration file:
```
[mqtt]
broker_addr = "x"
port = x
credentials = ["x", "x"]

[[cameras]]
name = "Argus"
username = "x"
password = "x"
uid = "x"
idle_disconnect = true
stream = "subStream"
[cameras.mqtt]
enable_motion = true
enable_preview = false
```
3. Launch Neolink:

**Versions**
Neolink software: [Neolink 0.6.3-rc.2]
Reolink camera model and firmware: Argus Eco

**Comment by QuantumEntangledAndy** [comment]
This is a duplicate. Google has removed the api we are using to register as a push notification server. Most info on it is available at #288
