### ISSUE TITLE
RTSP Password

### ISSUE THREAD

**Issue by Reddax** [QuantumEntangledAndy/neolink#297]
**Is your feature request related to a problem? Please describe.**
Currently, I can just use the IP address for the RTSP stream that neolink provides without needing any credentials.

**Describe the solution you'd like**
Could a feature be added to add a password to the RTSP stream that it provides, please?

**Comment by Reddax** [comment]
I realised it's in the complete config. Ignore me!

**Comment by QuantumEntangledAndy** [comment]
Just remember that unless you use rtsps (with TLS) the password is easily extracted by an attacker monitoring packets. The config for that is

```toml
certificate = "/path/to/pem/with/cert/and/key"
```

You would need to generate the key and certificate yourself and distribute the right public cert to the clients yourself
