### ISSUE TITLE
Help with translating to python for HomeAssistant

### ISSUE THREAD

**Issue by starkillerOG** [QuantumEntangledAndy/neolink#299]
I am the maintainer of the build-in Reolink integration.
I have just tested this neolink project and indeed I was able to turn on/off the HTTPS port on my Reolink cameras.
It would be very benificial for the HomeAssistant users of the Reolink integration if they did not need to turn on this HTTPS port on the cameras manually, especially for new users.
Therefore I am hoping to implement the Baichuan protocol (port 9000) in python to:
1) login to the camera
2) check which ports are available and which are enabled (HTTP, HTTPS, RTMP, RTSP, ONVIF)
3) enable the HTTPS port
4) logout

Unfortunately I am not familiar with Rust.
It would be a greath help for me if you would be willing to point me in the right direction.

I don't know if you are familiar with Python?
It would be amazing if you could write a (small as possible) python script that can login to the camera using the Baichuan protocol.
But even if you could provide the relevant simplified Rust code used by this library to make the login that would already be very helpfull (so small as possible just the login code, so I don't need to figure out the complete workings of this project).

Would you be willing to help me out a bit?

**Comment by QuantumEntangledAndy** [comment]
I'm quite familiar with python, so please let me know what issues you are facing. You what this in pure python or would you be ok with some FFI binding to neolink core?

**Comment by QuantumEntangledAndy** [comment]
I've got the protocol documented in `dissector/` have you read that?

**Comment by starkillerOG** [comment]
Thank you so much, amazing you are willing to help me out a bit.

Unfortunately I will need pure python. It will be part of a build-in HomeAssistant integration (not a add-on) so will need just python.

I read the docs under dissector, that is very very helpful.
I am just not so sure about the encryption part of the protocol.
But honestly I have not tried it out yet, will attempt first login this weekend.

**Comment by QuantumEntangledAndy** [comment]
Two possible paths for encryption

- find a package for it, not sure if there are any in pure python for this but i suspect ha already has some aes package in its requirement
- during login you can limit the maximum encryption you support, 0: no encryption (some camera refuse this), 1 bc encryption (trivial to write your own pure python encoding functions), 2+: aes needs external libs

**Comment by starkillerOG** [comment]
I have worked with encryption libs before, that's no issue. I was just wondering which part of the message and wich messages will be encrypted. But I will figure it out.

Especially if you would be willing to help me point in the right direction if I get stuck

**Comment by QuantumEntangledAndy** [comment]
Encryption starts at the 02 level, where the nonce is negotiated then is elevated to 03 with aes.

their are three parts to a message

- binary header
- extension payload (optional)
- message payload (optional)

When extension payload is present it is always encrypted

When message payload comes in two forms

- xml commands (always encrypted)
- binary

The binary payloads are described by the extension payload (`<binary>1<\binary>` set) and are present for video and some ptz. These may or may not be encrypted depending on if the flags are set in the extension xml

**Comment by starkillerOG** [comment]
@QuantumEntangledAndy I have started working on my first attempt at the initial legacy login message.

your docs state:

```
Send legacy login message

    User and pass MD5'ed
    Capped at 32 bytes with a null terminator
    Bytes 32 is always zero so only first 31 bytes are compared
```

But unfortunately that is not quite clear enough for me :(

Do I just concanate the username and password directly after each-other (nothing in-between) then cap it at 31 chars with a \0 at the end (or pad with \0 to a lenght of 32 chars). and then do the MD5-hash.
results in 16 bytes

Or do I do a seperate MD5-hash of the username and MD5-hash of the password and then combine them?
results in 32 bytes

When I look at a wireshark capture of your neolink program, the first message beeing send (which I am hoping is the legacy login) is actually 126 bytes long, so no idea where the other bytes are coming from.....

Moreover in the header of this captured message, between the message length ('2c070000') and the message class ('1465') there are all zeros. I would have expected a encryption_offset of '00000001' and encrypt '01' with the unknown 'dc' as in your docs. what is going on there?

**Comment by starkillerOG** [comment]
Oh and after I make the MD5-hash, should I then do some encryption of that body?
I do see the decrypt methods documented, but I do not see the encrypt method....

Sorry for beeing slow to pick this up...

**Comment by QuantumEntangledAndy** [comment]
The BCEncrypt cipher is symmetric in other words decrypt and encrypt are the same. 

For the hashing seem this comment in the source

https://github.com/QuantumEntangledAndy/neolink/blob/f15fdaefbcfe5cde3b0289c1e106cb85f6d3d39b/crates/core/src/bc_protocol.rs#L436-L443

The code below is

```rust
fn test_md5_string() {
    // Note that these literals are only 31 characters long - see explanation above.
    assert_eq!(
        md5_string("admin", Truncate),
        "21232F297A57A5A743894A0E4A801FC"
    );
    assert_eq!(
        md5_string("admin", ZeroLast),
        "21232F297A57A5A743894A0E4A801FC\0"
    );
}
```

Shows how their are too different ways BC handles hashes, one simple truncates to 31 chars instead of the usual 32 and the other replaces it with a `\0` 

```rust
fn md5_string(input: &str, trunc: Md5Trunc) -> String {
    let mut md5 = format!("{:X}\0", md5::compute(input));
    md5.replace_range(31.., if trunc == Truncate { "" } else { "\0" });
    md5
}
```

For login we need the `ZeroLast` with the legacy which upgrades to modern login that then uses `Truncate`

**Comment by QuantumEntangledAndy** [comment]
For testing start with `00 dc` that way no encryption is required (providing your camera allows that)

**Comment by QuantumEntangledAndy** [comment]
Here's the BCEncrypt in rust


```rust
const XML_KEY: [u8; 8] = [0x1F, 0x2D, 0x3C, 0x4B, 0x5A, 0x69, 0x78, 0xFF];

let key_iter = XML_KEY.iter().cycle().skip(offset as usize % 8);
key_iter
    .zip(buf)
    .map(|(key, i)| *i ^ key ^ (offset as u8))
    .collect()
```

The `offset` is stored in the header

**Comment by QuantumEntangledAndy** [comment]
Maybe this, but haven't tested 

```python
XML_KEY = [0x1F, 0x2D, 0x3C, 0x4B, 0x5A, 0x69, 0x78, 0xFF]

# .iter means iterate (for loop)
# .cycle means wrap around, so modulo
# .skip means well move forwards so +offset
def bccrypt(buf, offset):
  crypted = []
  for idx, b in enumerate(buf):
      key = XML_KEY[(offset + idx) % len(XML_KEY)]
      c = b ^ key ^ (offset)
      c = crypted.append(c)
  return crypted
```

**Comment by QuantumEntangledAndy** [comment]
Also its symmetic so test like this


```rust
let zeros: [u8; 256] = [0; 256];

let decrypted = EncryptionProtocol::BCEncrypt.encrypt(0, &zeros[..]);
let encrypted = EncryptionProtocol::BCEncrypt.decrypt(0, &decrypted[..]);
assert_eq!(encrypted, &zeros[..]);
```

**Comment by QuantumEntangledAndy** [comment]
> Do I just concanate the username and password directly after each-other (nothing in-between) then cap it at 31 chars with a \0 at the end (or pad with \0 to a lenght of 32 chars). and then do the MD5-hash.
results in 16 bytes

Yes concat `username + nonce`

```rust
let concat_username = format!("{}{}", credentials.username, nonce);
let concat_password = format!("{}{}", modern_password, nonce);
let md5_username = md5_string(&concat_username, Truncate);
let md5_password = md5_string(&concat_password, Truncate);
```

**Comment by QuantumEntangledAndy** [comment]
> When I look at a wireshark capture of your neolink program, the first message beeing send (which I am hoping is the legacy login) is actually 126 bytes long, so no idea where the other bytes are coming from.....

Assuming your using an older neolink which actually send the md5 hashed password rather than just the header. The legacy login message it is zero padded to 1836 bytes total

**Comment by QuantumEntangledAndy** [comment]
> Oh and after I make the MD5-hash, should I then do some encryption of that body?
I do see the decrypt methods documented, but I do not see the encrypt method....

Encrypt the body in every message body after the NONCE is received

**Comment by starkillerOG** [comment]
Thank you so much for all this extra info.

I started testing with only the header for the initial legacy login.

When I use for the encryption '00dc', '01dc', '02dc', '10dc', '11dc' I do not get any response.
When I use '12dc' I got my first response form the Reolink NVR !!!, however it does seem to be encrypted.

I am currently using a NVR because that was just conveniant, will take out a seperate camera for testing tonight, maybe that responds diffrently.

What does the encryption '12dc' mean and can I decrypt that withouth knowing the Nonce yet?

**Comment by QuantumEntangledAndy** [comment]
We are not sure what the 12dc means. We have also seen 21dc. I think the first part the 1 is the encryption and the 2 is some other flag.

**Comment by QuantumEntangledAndy** [comment]
If you go via an NVR the magic header is different.

**Comment by QuantumEntangledAndy** [comment]
In an nvr the channel number is more important too. It's zero based so the firs camera is at 0 and the second at 1 (despite how it's labelled as 1 and 2 in the camera view)

**Comment by QuantumEntangledAndy** [comment]
When possible maybe you can share your code on github and I'll see if I can test it

**Comment by starkillerOG** [comment]
@QuantumEntangledAndy thank you so much for the detailed help!

As a little update:
In the meantime I have been able to send the header, get back the response, decode it and extract the nonce.
I am very happy with the progress.

Next up is the modern login, looking forward to also getting that working.

**Comment by QuantumEntangledAndy** [comment]
Once you have the nonce your mostly there, so congratulations. Let me one if you need any more help.

**Comment by starkillerOG** [comment]
@QuantumEntangledAndy again, thank you so incredebly much for your assistance!

I now have the baichuan protocol fully working (including the AES encryption) in python.

You can see my implementation here: https://github.com/starkillerOG/reolink_aio/pull/80/files
I already integrated it into my reolink-aio library such that it will automatically open the HTTPs port when needed.
This will make the initial setup for new Home Assistant users even easier!

I will do some additional testing on diffrent camera models and will merge the PR soon.

**Comment by starkillerOG** [comment]
@QuantumEntangledAndy as you can see in the PR, I added you in the Acknowledgments section of the reolink-aio Readme.

Thanks again for the help.
I will close this issue now, hopefully I can reach out again in the future if I need further assistance with the baichuan protocol.

**Comment by starkillerOG** [comment]
@QuantumEntangledAndy one more question:
Do you know if it is possible to get the `80: <VersionInfo>` command for a IPC camera connected to a NVR instead of just the VersionInfo of the NVR itself?

**Comment by QuantumEntangledAndy** [comment]
Can you do it with the official app? If you look at version number in the official reolink app does it report the NVR or the camera? If so I can work it out from the wireshark packets

**Comment by starkillerOG** [comment]
No I did not find this info in the mobile app or desktop client, so I am guessing it is just not there.

I did receive a command ID 145 from my NVR containing a list of the connected channels with their UIDs and some info.
That would be really intresting, but I can't seem to figure out how to specifically request the cmd_id 145, it is just beeing send by the NVR upon connection, but if I try to request it I get a 405 status code: method not allowed.

**Comment by QuantumEntangledAndy** [comment]
If it's not in the client likely it's not there. You could try adding an extension xml with the channel number you want.

But there are a bunch of details you just have to store on an initial connection.

**Comment by QuantumEntangledAndy** [comment]
Try this for the extension xml along with the rest in `VersionInfo 80`

```xml
  <?xml version="1.0" encoding="UTF-8" ?>
  <Extension version="1.1">
  <channelId>0</channelId>
  </Extension>
  ```

**Comment by QuantumEntangledAndy** [comment]
Most extension XMLs are used to select the channel in an NVR so without any luck it will work

**Comment by starkillerOG** [comment]
I tried adding the extension xml, but that did not help.

Not to big of a fan of needing to catch that intial packet, if I miss it I can't retry. But apperently thats just the way it is.

I just published a new reolink-aio version which includes the baichuan API, thanks for all your help.

**Comment by QuantumEntangledAndy** [comment]
Congrats on the release, glad I could help. Let me know if you ever have anything else fun you want to do with it :)


Also, since it is TCP you can't miss it all messages are confirmed by read receipts or else they are automatically resent by the protocol. What can happen is the whole TCP connection dies in which case you would probably want a full retry anyways

**Comment by el3ctrician** [comment]
Thanks to both of you guys really great work. i came here since i was searching for a plugin to Home assitant that uses the Baichuan directly without RTSP in between. My HA hardware is very low (RPI3) and running RTSP is killing it so since all the data is retrived through Baichuan as per my understanding and the commands are "translated to python" can i just open the stream and start capturing it and maybe use a lighter framing techninque to HA ?
