### ISSUE TITLE
Remove the .DS_Store file

### ISSUE THREAD

**Issue by dkerr64** [QuantumEntangledAndy/neolink#34]
One of your push's yesterday created a .DS_Store file (generated by apple Mac) which because I also use a Mac is updated by me and so git thinks I have modified a file under version control, so I cannot switch branches without deleting it first.  Can you delete them please.  You might want to also add these files to your `.gitignore_global` file to avoid this in future.

Edited to add... or the `.gitignore` in this repository.
Thanks.

**Comment by dkerr64** [comment]
FYI... here is my global git ignore...

```
.DS_Store
._.DS_Store
**/.DS_Store
**/._.DS_Store
```

**Comment by QuantumEntangledAndy** [comment]
Whaaa I thought that was in my gitignore already. Sorry it snuck though.

**Comment by QuantumEntangledAndy** [comment]
Should be done

**Comment by dkerr64** [comment]
Yes, thank you!
