### ISSUE TITLE
Change message reporting IP address discovery from debug level to info level

### ISSUE THREAD

**Issue by dkerr64** [QuantumEntangledAndy/neolink#39]
I suggest making the IP address discovery messages info level.  Like...
https://github.com/dkerr64/neolink/commit/2ad9e02457e6db10bd57bf0010c1f24a60e0cc39

Thanks,
David

**Comment by QuantumEntangledAndy** [comment]
Ok sure, suppose it will help determine which method users are using on the bug reports
