### ISSUE TITLE
Pir status

### ISSUE THREAD

**Issue by fmarzocca** [QuantumEntangledAndy/neolink#50]
Is it possible to query the PIR status?

**Comment by QuantumEntangledAndy** [comment]
Currently not but it should be an easy thing to add once I have some time.

**Comment by fmarzocca** [comment]
Great! Thank you

**Comment by QuantumEntangledAndy** [comment]
Might I ask what it is you are trying to achieve? I might be able to get an idea for how to present the data if I know how you want to use it

**Comment by QuantumEntangledAndy** [comment]
p.s. lets keep this issue open until it is merged

**Comment by fmarzocca** [comment]
Simple. Just integrate the PIR status into my NodeRed automation. So in the Dashboard I could see the current status and switch it if I need.

**Comment by QuantumEntangledAndy** [comment]
Can node red parse XML data from stdout? The camera uses xml for configuration and it would be easist to pass that along.

**Comment by fmarzocca** [comment]
Not from stdout. I can parse XML if I receive it as a function return.

**Comment by QuantumEntangledAndy** [comment]
Add in #53

```bash
neolink pir --config=config.toml
```

while omitting the on/off will report the current PIR status in xml format
