### ISSUE TITLE
Install on Windows 11

### ISSUE THREAD

**Issue by Veuchez** [QuantumEntangledAndy/neolink#52]
When I try to start neolink on Windows 11 I get these errors

![dll error](https://user-images.githubusercontent.com/59020055/229214466-af4c0371-6e6a-4cc7-8c88-6a36f226aced.png)

In the gstreamer folder these dlls are actually not there.
I tried to install both MSVC 64-bit version and MinGW 64-bit version, the result I get is the same.
I tried with gstreamer 1.20.5 with gstreamer 1.20.6, 1.22.1 and many others
Where am I wrong?

**Comment by QuantumEntangledAndy** [comment]
When you are installing gstreamer did you select the "Full" installation mode. It's not the default install and you need to activly select it

**Comment by Veuchez** [comment]
Yes sure, complete.

**Comment by QuantumEntangledAndy** [comment]
Wait so you do have them in the folder? 

Just confirming because you said 

| In the gstreamer folder these dlls are actually not there.

Anyways if they are there. Then you just need to set the PATH environmental variable. Do you know how to do this?

**Comment by Veuchez** [comment]
![variabili](https://user-images.githubusercontent.com/59020055/229293134-11bd7c30-c74f-43ef-a5e1-88b366bc7842.png)

I think it should be right..
Installation Path: C:\gstreamer\1.0\mingw_x86_64\bin

**Comment by QuantumEntangledAndy** [comment]
If you do it like this. Make sure you set GSTREAMER_ROOT_X86_64 variable too.

**Comment by Veuchez** [comment]
Isn't it right how I set it?

**Comment by QuantumEntangledAndy** [comment]
Your picture sets it as

`%GSTREAMER_ROOT_X86_64%\bin`

Written like this it means.

Read the environmental variable `GSTREAMER_ROOT_X86_64` and replace `%GSTREAMER_ROOT_X86_64%` with the contents of that variable.

If you want to do it this way. Make sure that the environmental variable `GSTREAMER_ROOT_X86_64` is set to the path where the root of gstreamer is

**Comment by Veuchez** [comment]
Not even if I set the environment variable so I solve the problem.
I have also tried in Windows 10 and am getting the same errors.
I don't understand where I'm wrong.
![variabili2](https://user-images.githubusercontent.com/59020055/229351151-f7ca50df-2361-4310-822b-b9496ec5740b.png)

**Comment by Veuchez** [comment]
Fixed by installing the MSVC version and copying Neolink inside the gstreamer "bin" folder.
From there Neolnk starts without dll errors.

**Comment by MRobi1** [comment]
@QuantumEntangledAndy What is the proper PATH environment variable to set?
I've tried all variations of
%GSTREAMER_1_0_ROOT_X86_64%\bin
GSTREAMER_1_0_ROOT_X86_64\bin
%GSTREAMER_ROOT_X86_64%
GSTREAMER_ROOT_X86_64

And I've set all variations of these paths to each
C:\gstreamer
C:\gstreamer\
C:\gstreamer\1.0
C:\gstreamer\1.0\
C:\gstreamer\1.0\msvc_x86_64
C:\gstreamer\1.0\msvc_x86_64\
C:\gstreamer\1.0\msvc_x86_64\bin
C:\gstreamer\1.0\msvc_x86_64\bin\

Example:
![image](https://github.com/QuantumEntangledAndy/neolink/assets/34860474/d560db4a-9d61-4825-a46f-a0dc62b8ca46)

If I click on the .exe I get the same set of 4 dll's not found. When I execute ./neolink rtsp --config=neolink.toml via powershell I get no feedback. Installed gstreamer using "complete" and can confirm all needed files are in C:\gstreamer\1.0\msvc_x86_64\bin\

Moving the neolink files into the gstreamer bin directory and execute via powershell and neolink starts and runs without issue. So it's definitely something I'm doing wrong with the PATH Environment Variable
