### ISSUE TITLE
Missing required gstreamer plugin `Unknown` for `textoverlay` element on Docker

### ISSUE THREAD

**Issue by omnone** [QuantumEntangledAndy/neolink#59]
Hi @QuantumEntangledAndy , I try to run the latest docker image by running this command:
```
docker run \
  -p 8554:8554 \
  --restart=on-failure \
  --volume=$PWD/config.toml:/etc/neolink.toml \
  quantumentangledandy/neolink
```
But I get the following error:

```
2023-04-13T14:02:11Z INFO  neolink::rtsp::states::loggedin] reolink_2: Camera reports firmware version v2.0.0.705_21052800
[2023-04-13T14:02:11Z INFO  neolink::rtsp::states::streaming] reolink_2: Starting video stream Main Stream (Clear)
[2023-04-13T14:02:16Z WARN  neolink::rtsp] reolink_1: Retryable error: reolink_1: Could not connect to camera
    
    Caused by:
        0: Failed to connect to camera reolink_1 at UID: 95270004UK0R1BGD on channel 0
        1: Cannot contact camera at given address
thread '<unnamed>' panicked at 'Could not build pipeline: Missing required gstreamer plugin `Unknown` for `textoverlay` element

Caused by:
    Failed to find element factory with name 'textoverlay' for creating element', src/rtsp/gst/factory.rs:157:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

Any help would be appreciated, thanks!

**Comment by omnone** [comment]
I've installed all the depedencies for gstreamer (not sure which one did the trick) and it seems to be working now. By the way I want to thank you for your time and effort on this project !
`apt-get install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libgstreamer-plugins-bad1.0-dev gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio`

**Comment by QuantumEntangledAndy** [comment]
I'll be trying to work out exactly which one it is in today and have the docker updated.

**Comment by QuantumEntangledAndy** [comment]
It is the `gstreamer1.0-x` (x11) package

**Comment by QuantumEntangledAndy** [comment]
I've add it to the docker image should be able to use that again in about an hour once this [build](https://github.com/QuantumEntangledAndy/neolink/actions/runs/4695706127) goes through
