### ISSUE TITLE
starting MQTT with docker image

### ISSUE THREAD

**Issue by jsapede** [QuantumEntangledAndy/neolink#65]
after adjusting some parameters for the docker file to be ok, i searched how to launch MQTT connexion

It looks like MQTT connexion is a specific extra execution of neolink, and that docker image includes a harcoded execution of neolink for RTSP only.

Would it be possible to launch MQTT at the same time than RTSP with docker ? isn't it possible inside the same execution of neolink ?

**Comment by QuantumEntangledAndy** [comment]
It'a currently designed as two separate sub commands. To get them to run at the same time would require a bit of rework on the code.

But starting two commands in one docker wouldn't be too much work. Put the first command on the background then start the second. It's not something I'm going to add to the default image though.

If you want to adjust the image just make a new docker file with the current neolink image as base and customise the entry point to start both commands.
