### ISSUE TITLE
"stop" PTZ Command missing

### ISSUE THREAD

**Issue by AdrianosBates** [QuantumEntangledAndy/neolink#71]
To provide some background to my issue, PTZ control over MQTT was not working for me prior to the recent update to this repo  involving updating MQTT to use tokio (I think?). However, after this update PTZ over MQTT seemed to be working somewhat reliably. However the camera seems to endlessly rotate no matter the speed. After some investigation with Wireshark and the Reolink desktop application, it seems that a 'stop' direction is sent when the user stops applying input to the PTZ commands.

To reproduce, I simply send a currently implemented PTZ command with MQTT, and the camera pans the expected way, although entirely to its limit unable to stop at a desired location.

Expected behavior should be that either the camera pans a specified amount before stopping, or a follow-up stop message should be sent by the user to cease the camera's motion. 

Forgive me if I have missed something here, or I am using the software incorrectly in some way, as I've only just started to play around with Neolink within the past week or so. I may try and implement this myself over the weekend if no one has the time.

**Comment by QuantumEntangledAndy** [comment]
If you can PR this would be great. I'm currently working on making VLC clients more reliable. Will likely take me a week to finish that. After that I've got plans to make the camera disconnect when paused to save battery. Then maybe try to work on a less battery intensive motion detection. So the todo list is quite large :).

**Comment by AdrianosBates** [comment]
Unfortunately, I cannot for the life of me figure out how to compile neolink on windows. If anyone has any tips for that, let me know. Otherwise, giving up on this for now.
