### ISSUE TITLE
Change the port

### ISSUE THREAD

**Issue by moskovskiy82** [QuantumEntangledAndy/neolink#75]
Error: Failed to parse the "/etc/neolink.toml" config file
Caused by:
    TOML parse error at line 2, column 14
      |
    2 |  bind_port = "8551" 
      |              ^^^^^^
    invalid type: string "8551", expected u16

Expected to the original docs that the port will be changed

**Comment by QuantumEntangledAndy** [comment]
No quotes around the number. Quotes make it a string

**Comment by moskovskiy82** [comment]
Solved. Mind putting that in the docs? Original docs are also unclear

**Comment by QuantumEntangledAndy** [comment]
If you want to make a PR for the docs please do. Most of the docs for the config though are in the sample_config.toml
