### ISSUE TITLE
Reoling E1 PRO mqtt/ptz not working

### ISSUE THREAD

**Issue by sanchosk** [QuantumEntangledAndy/neolink#81]
**Describe the bug**
I used your amazing SW to control my Reolink E1 PRO.
The camera reacts to the first command using MQTT, then stops responding.
Any movement using ptz results in maximum turn, no matter what number I use in the message.
E.g.
mosquitto_pub -h mqttserver -t "neolink/camera1/control/ptz" -m "Right 2"
starts to turn the camera and rotates to max right, then stops.
Further commands (e.g. rotate to left) result in no movement at all. I have to stop the neolink and start it again to again react to command

**To Reproduce**
Steps to reproduce the behavior. Example:
1. Create this configuration file: - standard config for E1 PRO and MQTT server
2. Launch Neolink: ./neolink -c neolink.toml mqtt
3. send message as in the example above
4. observe the camera

**Expected behavior**
The camera will rotate a bit to the right, then stop and listen to next command.

**Actual behavior**
Camera rotates to max right position and stops listening to MQTT commands.

**Versions**
NVR software: n/a
Neolink software: 42ff221b0735bf55fbf9ba2508329ef1fdb540e9 release
Reolink camera model and firmware: E1 PRO v3.1.0.1414_22101301

**Comment by QuantumEntangledAndy** [comment]
I think this is being worked on already in #72

**Comment by sanchosk** [comment]
Any idea when that code will be merged, so I can perhaps test it?

**Comment by QuantumEntangledAndy** [comment]
Merged now, will be in the 0.5.10 release probably in about an hour or so

**Comment by sanchosk** [comment]
Installed and tested - works GREAT now, tried "left 1", "down 3" and back "right 1" and "up 3" and I ended up exactly at the starting position. No need to restart MQTT connection anymore.
Thanks a lot for the effort.
Any chance to get you a coffee for this? Without this SW, I would have to throw the camera away as it would not be usable for me anymore...

**Comment by QuantumEntangledAndy** [comment]
I've got a kofi account on my profile but perhaps you could send something to https://github.com/AdrianosBates he's the one who worked up the PR to fix this. Not sure if he's got a kofi though.
